# SPDX-FileCopyrightText: 2024 SUSE LLC
#
# SPDX-License-Identifier: BSD3

name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  release:
    types:
      - published

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: 0

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 #v6.0.0
      with:
        go-version: '1.24.1'

    - name: Build
      run: |
        mkdir -p ./bin
        go build -o ./bin/ -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload binaries
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      with:
        name: binaries
        path: ./bin/*
